name: test

on:
  push:
    branches-ignore:
      - renovate/**
  pull_request:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5
        with:
          go-version-file: "go.mod"

      - name: Go Build Cache (build)
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg
          key: go-cache-119-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-cache-119-

      - run: go test -race -count=5 ./...
